### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by RoyiAvital** [chummersone/boxPlot#7]
Could you add release notes in the MD file of the project?

Thank You.

**Comment by chummersone** [comment]
Personally, I don't think that the readme is the place for release notes. But I have been slack at tagging and using GitHub's built-in releases tools. So I've added a new tag (this ensure that release info travels with with repo) and added a release that includes some notes. I'll be sure to do this more regularly.

**Comment by RoyiAvital** [comment]
But this will work for people working with GitClient.

What about someone who just want to download the files?
How can he know the features added / removed.
The version he has and if he needs to update.

Think of it not only as the repository of your files, but also the product page of the tool.

**Comment by chummersone** [comment]
> What about someone who just want to download the files?

Clicking on "releases" reveals the release notes.

> The version he has and if he needs to update.

That's a good point. When the files were hosted in Subversion, they would automatically be tagged with a revision number, but such functionality doesn't exist in Git. I take your point and will add release notes.
